[package]
name = "lending_data-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.lending_data]
path = ".."

[dependencies.elrond-wasm]
version = "0.10.2"

[dependencies.elrond-wasm-debug]
version = "0.10.2"
